name: SkyTools
depend: [Libraries, SkyCore]
softdepend: [Multiverse-Core]
version: '1.0'
main: fr.entasia.skytools.Main
commands:

  skytools:

  speedwriter:

  warp:
    aliases: [warps]

  customarrow:
    aliases: [customarrows]

  customenchant:
    aliases: [customenchants]

  cosmetiques:
    aliases: [cosm,cosmetique,pet,pets,particules]

  tpa:
    aliases: [tpas]

  tpaccept:
    aliases: [tpyes]

  tpdeny:
    aliases: [tpno, tpadeny]